a = "Welcome to the Interesting World of Python Programming"
print(a)
b = ( "Are you interested in playing a Puzzle with me \nEnter Yes or No")
print(b)
c = input()
print( "OK Thens Lets get Started")
print("Think a number between 1 to 10" )
print("If You thought it then write Yes or No")
c = input()
print("Now multiply it by 2")
print("I know you are very Clever But I am also very Clever")
print("If You Multiplied it then write Yes or No")
c = input()
print("Now multiply it by 5")
print("I Know you are enjoying this \nIf You Multiplied it then write Yes or No")
c = input()
print("Now divide it by original number")
print("If You completed your divison then write Yes or No(hehehehe)")
c = input()
print("Now Subtract 7 from it")
print("Kesa dia phir nhi dia acha")
c = input()
print("You Thought about of Number 3")
print("Chass ayi k ni Bawa g Sachi Sachi Dasna A")